import Foundation

enum AppLocalizedKey: String {
    case settingsTitle
    case settingsLanguage
    case settingsLanguageAuto
    case settingsAppearance
    case settingsChatTitle
    case settingsChatStyle
    case settingsDeleteHistory
    case settingsDeleteHistoryAction
    case settingsDeleteHistoryTitle
    case settingsDeleteHistoryMessage
    case settingsDeleteHistoryConfirm
    case settingsRestoreDefaults
    case settingsRestoreDefaultsAction
    case settingsRestoreDefaultsTitle
    case settingsRestoreDefaultsMessage
    case settingsRestoreDefaultsConfirm
    case appearanceLight
    case appearanceDark
    case appearanceSystem
    case chatTitleModeContent
    case chatTitleModeAI
    case chatStyleDefault
    case chatStyleEfficiency
    case chatStyleEnthusiasm
    case chatStyleGentle
    case chatStyleSerious
    case sidebarHistory
    case sidebarNewConversation
    case sidebarEmptyHistory
    case sidebarSettings
    case moduleStatusWaiting
    case moduleStatusLoading
    case moduleStatusReady
    case moduleStatusError
    case moduleLoad
    case moduleUnload
    case moduleLoadingOverlay
    case contextLengthTitle
    case contextLengthShort
    case contextLengthMedium
    case contextLengthLong
    case contextLengthCustom
    case contextLengthCustomPlaceholder
    case contextLengthCustomMessage
    case contextLengthCustomWarning
    case contextLengthCustomWarningConfirm
    case reasoningThinking
    case reasoningDirect
    case attachmentPickImage
    case composerPlaceholder
    case renameTitle
    case renamePlaceholder
    case commonCancel
    case commonSave
    case renameMessage
    case historyCustomTitle
    case historyAITitleGenerate
    case historyAITitleGenerating
    case historyDeleteConversation
    case gallerySelectedImages
    case galleryConversationImages
    case assistantStoppedThinking
    case attachmentImageProcessingWait
    case attachmentImageProcessingStopped
    case attachmentImageWarning
    case attachmentImageWarningConfirm
    case settingsThinkingMode
    case thinkingModeEnabled
    case thinkingModeDisabled
    case thinkingModeWarning
    case thinkingModeWarningConfirm
    case thinkingModeLockedHint
}
