import Foundation

enum LocalizationCatalog {
    static func text(_ key: AppLocalizedKey, language: AppLanguage) -> String {
        translations[language]?[key]
        ?? translations[.english]?[key]
        ?? key.rawValue
    }

    private static let translations: [AppLanguage: [AppLocalizedKey: String]] = [
        .english: [
            .settingsTitle: "Settings",
            .settingsLanguage: "Language",
            .settingsAppearance: "Theme",
            .settingsChatTitle: "Chat Title",
            .settingsChatStyle: "Chat Style",
            .settingsLanguageAuto: "Auto (%@)",
            .settingsDeleteHistory: "Delete History",
            .settingsDeleteHistoryAction: "Delete",
            .settingsDeleteHistoryTitle: "Delete All Local History",
            .settingsDeleteHistoryMessage: "Chat history is stored only on this device. Deleting all history cannot be undone.\n\n(This really cannot be undone 😊~)\n\nPlease confirm that you want to delete all history.",
            .settingsDeleteHistoryConfirm: "Delete",
            .settingsRestoreDefaults: "Restore Defaults",
            .settingsRestoreDefaultsAction: "Restore",
            .settingsRestoreDefaultsTitle: "Restore Default Settings",
            .settingsRestoreDefaultsMessage: "Restore the default language, theme, chat title option, chat style, and context length.\n\nThis action cannot be undone.",
            .settingsRestoreDefaultsConfirm: "Confirm",
            .appearanceLight: "Light",
            .appearanceDark: "Dark",
            .appearanceSystem: "Follow System",
            .chatTitleModeContent: "Default Conversation Text",
            .chatTitleModeAI: "AI Auto-Title for New Chats",
            .chatStyleDefault: "Default",
            .chatStyleEfficiency: "Efficient",
            .chatStyleEnthusiasm: "Enthusiastic",
            .chatStyleGentle: "Gentle",
            .chatStyleSerious: "Serious",
            .sidebarHistory: "Local Chat History",
            .sidebarNewConversation: "New Chat",
            .sidebarEmptyHistory: "No local chat history yet",
            .sidebarSettings: "Settings",
            .moduleStatusWaiting: "Waiting",
            .moduleStatusLoading: "Loading",
            .moduleStatusReady: "Ready",
            .moduleStatusError: "Error",
            .moduleLoad: "Load",
            .moduleUnload: "Unload",
            .moduleLoadingOverlay: "Loading",
            .contextLengthTitle: "Context Length",
            .contextLengthShort: "Short Chat",
            .contextLengthMedium: "Medium Chat",
            .contextLengthLong: "Long Chat",
            .contextLengthCustom: "Custom",
            .contextLengthCustomPlaceholder: "Enter token count",
            .contextLengthCustomMessage: "Range: 100–262143",
            .contextLengthCustomWarning: "A context that is too short (<4K) will cause conversations to be cut off prematurely, resulting in a poor experience.\n\nA context that is too long (>32K) puts excessive pressure on the device hardware and may cause overheating, lag, or crashes.\n\nPlease balance your personal needs and device capabilities when setting the maximum context, and accept any potential negative effects.",
            .contextLengthCustomWarningConfirm: "I Understand",
            .reasoningThinking: "Thinking",
            .reasoningDirect: "Direct",
            .attachmentPickImage: "Pick Images",
            .composerPlaceholder: "Type a message...",
            .renameTitle: "Custom Title",
            .renamePlaceholder: "Enter a custom title",
            .commonCancel: "Cancel",
            .commonSave: "Save",
            .renameMessage: "Set a shorter title for this conversation.",
            .historyCustomTitle: "Custom Title",
            .historyAITitleGenerate: "Generate AI Title",
            .historyAITitleGenerating: "Generating Title",
            .historyDeleteConversation: "Delete Conversation",
            .gallerySelectedImages: "Selected Images",
            .galleryConversationImages: "Conversation Images",
            .assistantStoppedThinking: "(The user has stopped my thinking)",
            .attachmentImageProcessingWait: "(Processing, please wait patiently)",
            .attachmentImageProcessingStopped: "The user has stopped me from analyzing the image. Please upload it again if you want to continue.",
            .attachmentImageWarning: "The current model has limited image understanding. Each image consumes a significant amount of context tokens. When images are attached, the model will automatically use Direct Answer mode (thinking is disabled).\n\nPlease be mindful of these limitations.",
            .attachmentImageWarningConfirm: "I Understand",
            .settingsThinkingMode: "Thinking Mode",
            .thinkingModeEnabled: "Enabled",
            .thinkingModeDisabled: "Disabled",
            .thinkingModeWarning: "Thinking mode allows the model to reason step-by-step before answering, which can improve response quality for complex questions.\n\nHowever, thinking mode significantly increases token consumption and generation time. On devices with limited hardware, it may cause noticeable lag or overheating.\n\nPlease balance quality needs and device capabilities.",
            .thinkingModeWarningConfirm: "Enable",
            .thinkingModeLockedHint: "Thinking mode is currently disabled. Please go to Settings to enable it first."
        ],
        .chineseSimplified: [
            .settingsTitle: "设置",
            .settingsLanguage: "语言",
            .settingsAppearance: "主题颜色",
            .settingsChatTitle: "聊天标题",
            .settingsChatStyle: "聊天风格",
            .settingsLanguageAuto: "自动（%@）",
            .settingsDeleteHistory: "一键删除历史记录",
            .settingsDeleteHistoryAction: "删除",
            .settingsDeleteHistoryTitle: "一键删除历史记录",
            .settingsDeleteHistoryMessage: "聊天记录均只储存在此设备上，删除所有历史记录后不可撤回。\n\n（真的不可撤回哦😊～）\n\n请确认是否要删除所有历史记录。",
            .settingsDeleteHistoryConfirm: "删除",
            .settingsRestoreDefaults: "恢复默认设置",
            .settingsRestoreDefaultsAction: "恢复",
            .settingsRestoreDefaultsTitle: "恢复默认设置",
            .settingsRestoreDefaultsMessage: "恢复到默认的语言设置，主题颜色，聊天标题选项，聊天风格，上下文长度选项。\n\n且该操作不可撤销。",
            .settingsRestoreDefaultsConfirm: "确认",
            .appearanceLight: "浅色",
            .appearanceDark: "深色",
            .appearanceSystem: "跟随系统",
            .chatTitleModeContent: "默认聊天内容作为标题",
            .chatTitleModeAI: "AI为后续聊天自动生成标题",
            .chatStyleDefault: "默认",
            .chatStyleEfficiency: "效率",
            .chatStyleEnthusiasm: "热情",
            .chatStyleGentle: "温柔",
            .chatStyleSerious: "认真",
            .sidebarHistory: "本地历史会话",
            .sidebarNewConversation: "新会话",
            .sidebarEmptyHistory: "暂无本地聊天历史",
            .sidebarSettings: "设置",
            .moduleStatusWaiting: "等待",
            .moduleStatusLoading: "载入",
            .moduleStatusReady: "就绪",
            .moduleStatusError: "异常",
            .moduleLoad: "加载",
            .moduleUnload: "卸载",
            .moduleLoadingOverlay: "加载中",
            .contextLengthTitle: "上下文长度",
            .contextLengthShort: "短对话",
            .contextLengthMedium: "中对话",
            .contextLengthLong: "长对话",
            .contextLengthCustom: "自定义",
            .contextLengthCustomPlaceholder: "输入 token 数量",
            .contextLengthCustomMessage: "范围：100–262143",
            .contextLengthCustomWarning: "自定义上下文太短（<4K）会导致对话被过早打断，无法获得良好体验。\n\n自定义上下文太长（>32K）对设备硬件压力过大，可能会出现发热、卡顿甚至闪退的现象。\n\n请权衡您的个人需求与设备配置来填写适当的最大上下文，并接受可能带来的负面效果。",
            .contextLengthCustomWarningConfirm: "我已知晓",
            .reasoningThinking: "思考",
            .reasoningDirect: "直答",
            .attachmentPickImage: "选图",
            .composerPlaceholder: "输入消息...",
            .renameTitle: "自定义标题",
            .renamePlaceholder: "输入自定义标题",
            .commonCancel: "取消",
            .commonSave: "保存",
            .renameMessage: "为当前会话设置一个更短的标题。",
            .historyCustomTitle: "自定义标题",
            .historyAITitleGenerate: "AI生成标题",
            .historyAITitleGenerating: "标题生成中",
            .historyDeleteConversation: "删除会话",
            .gallerySelectedImages: "待发送图片",
            .galleryConversationImages: "会话图片",
            .assistantStoppedThinking: "(用户已经停止让我思考)",
            .attachmentImageProcessingWait: "（处理中请耐心等待）",
            .attachmentImageProcessingStopped: "用户已停止让我分析图片，如需继续分析请重新上传。",
            .attachmentImageWarning: "当前模型对图片的理解能力有限，每张图片会占用大量上下文token。附带图片时，模型将自动使用直答模式（思考功能会被关闭）。\n\n请注意以上限制。",
            .attachmentImageWarningConfirm: "我已知晓",
            .settingsThinkingMode: "思考模式",
            .thinkingModeEnabled: "已启用",
            .thinkingModeDisabled: "已关闭",
            .thinkingModeWarning: "思考模式允许模型在回答前逐步推理，可以提升复杂问题的回答质量。\n\n但思考模式会显著增加token消耗和生成时间。在硬件配置有限的设备上，可能会出现明显的卡顿或发热现象。\n\n请权衡质量需求与设备性能。",
            .thinkingModeWarningConfirm: "启用",
            .thinkingModeLockedHint: "思考模式当前未启用，请先前往设置中开启。"
        ],
        .chineseTraditional: [
            .settingsTitle: "設定",
            .settingsLanguage: "語言",
            .settingsAppearance: "主題顏色",
            .settingsChatTitle: "聊天標題",
            .settingsChatStyle: "聊天風格",
            .settingsLanguageAuto: "自動（%@）",
            .settingsDeleteHistory: "一鍵刪除歷史記錄",
            .settingsDeleteHistoryAction: "刪除",
            .settingsDeleteHistoryTitle: "一鍵刪除歷史記錄",
            .settingsDeleteHistoryMessage: "聊天記錄均只儲存在此裝置上，刪除所有歷史記錄後不可撤回。\n\n（真的不可撤回哦😊～）\n\n請確認是否要刪除所有歷史記錄。",
            .settingsDeleteHistoryConfirm: "刪除",
            .settingsRestoreDefaults: "恢復預設設定",
            .settingsRestoreDefaultsAction: "恢復",
            .settingsRestoreDefaultsTitle: "恢復預設設定",
            .settingsRestoreDefaultsMessage: "恢復到預設的語言設定、主題顏色、聊天標題選項、聊天風格、上下文長度選項。\n\n且此操作不可撤銷。",
            .settingsRestoreDefaultsConfirm: "確認",
            .appearanceLight: "淺色",
            .appearanceDark: "深色",
            .appearanceSystem: "跟隨系統",
            .chatTitleModeContent: "預設聊天內容作為標題",
            .chatTitleModeAI: "AI為後續聊天自動生成標題",
            .chatStyleDefault: "預設",
            .chatStyleEfficiency: "效率",
            .chatStyleEnthusiasm: "熱情",
            .chatStyleGentle: "溫柔",
            .chatStyleSerious: "認真",
            .sidebarHistory: "本地歷史會話",
            .sidebarNewConversation: "新會話",
            .sidebarEmptyHistory: "暫無本地聊天歷史",
            .sidebarSettings: "設定",
            .moduleStatusWaiting: "等待",
            .moduleStatusLoading: "載入",
            .moduleStatusReady: "就緒",
            .moduleStatusError: "異常",
            .moduleLoad: "加載",
            .moduleUnload: "卸載",
            .moduleLoadingOverlay: "載入中",
            .contextLengthTitle: "上下文長度",
            .contextLengthShort: "短對話",
            .contextLengthMedium: "中對話",
            .contextLengthLong: "長對話",
            .contextLengthCustom: "自訂",
            .contextLengthCustomPlaceholder: "輸入 token 數量",
            .contextLengthCustomMessage: "範圍：100–262143",
            .contextLengthCustomWarning: "自訂上下文太短（<4K）會導致對話被過早打斷，無法獲得良好體驗。\n\n自訂上下文太長（>32K）對裝置硬體壓力過大，可能會出現發熱、卡頓甚至閃退的現象。\n\n請權衡您的個人需求與裝置配置來填寫適當的最大上下文，並接受可能帶來的負面效果。",
            .contextLengthCustomWarningConfirm: "我已知曉",
            .reasoningThinking: "思考",
            .reasoningDirect: "直答",
            .attachmentPickImage: "選圖",
            .composerPlaceholder: "輸入消息...",
            .renameTitle: "自訂標題",
            .renamePlaceholder: "輸入自訂標題",
            .commonCancel: "取消",
            .commonSave: "儲存",
            .renameMessage: "為當前會話設定一個更短的標題。",
            .historyCustomTitle: "自訂標題",
            .historyAITitleGenerate: "AI生成標題",
            .historyAITitleGenerating: "標題生成中",
            .historyDeleteConversation: "刪除會話",
            .gallerySelectedImages: "待發送圖片",
            .galleryConversationImages: "會話圖片",
            .assistantStoppedThinking: "(使用者已經停止讓我思考)",
            .attachmentImageProcessingWait: "（處理中請耐心等待）",
            .attachmentImageProcessingStopped: "使用者已停止讓我分析圖片，如需繼續分析請重新上傳。",
            .attachmentImageWarning: "當前模型對圖片的理解能力有限，每張圖片會佔用大量上下文token。附帶圖片時，模型將自動使用直答模式（思考功能會被關閉）。\n\n請注意以上限制。",
            .attachmentImageWarningConfirm: "我已知曉",
            .settingsThinkingMode: "思考模式",
            .thinkingModeEnabled: "已啟用",
            .thinkingModeDisabled: "已關閉",
            .thinkingModeWarning: "思考模式允許模型在回答前逐步推理，可以提升複雜問題的回答品質。\n\n但思考模式會顯著增加token消耗和生成時間。在硬體配置有限的裝置上，可能會出現明顯的卡頓或發熱現象。\n\n請權衡品質需求與裝置效能。",
            .thinkingModeWarningConfirm: "啟用",
            .thinkingModeLockedHint: "思考模式當前未啟用，請先前往設定中開啟。"
        ],
        .japanese: [
            .settingsTitle: "設定",
            .settingsLanguage: "言語",
            .settingsAppearance: "テーマ",
            .settingsChatTitle: "チャットタイトル",
            .settingsChatStyle: "会話スタイル",
            .settingsLanguageAuto: "自動（%@）",
            .settingsDeleteHistory: "一括で履歴を削除",
            .settingsDeleteHistoryAction: "削除",
            .settingsDeleteHistoryTitle: "一括で履歴を削除",
            .settingsDeleteHistoryMessage: "チャット履歴はこの端末にのみ保存されています。すべての履歴を削除すると取り消せません。\n\n（本当に取り消せませんよ😊～）\n\nすべての履歴を削除してよいか確認してください。",
            .settingsDeleteHistoryConfirm: "削除",
            .settingsRestoreDefaults: "デフォルト設定に戻す",
            .settingsRestoreDefaultsAction: "復元",
            .settingsRestoreDefaultsTitle: "デフォルト設定に戻す",
            .settingsRestoreDefaultsMessage: "言語設定、テーマカラー、チャットタイトルの設定、会話スタイル、コンテキスト長をデフォルトに戻します。\n\nこの操作は元に戻せません。",
            .settingsRestoreDefaultsConfirm: "確認",
            .appearanceLight: "ライト",
            .appearanceDark: "ダーク",
            .appearanceSystem: "システムに従う",
            .chatTitleModeContent: "デフォルトの会話内容をタイトルにする",
            .chatTitleModeAI: "AIが新規チャットのタイトルを自動生成",
            .chatStyleDefault: "標準",
            .chatStyleEfficiency: "効率",
            .chatStyleEnthusiasm: "熱意",
            .chatStyleGentle: "優しさ",
            .chatStyleSerious: "真剣",
            .sidebarHistory: "ローカル会話履歴",
            .sidebarNewConversation: "新規チャット",
            .sidebarEmptyHistory: "ローカル会話履歴はまだありません",
            .sidebarSettings: "設定",
            .moduleStatusWaiting: "待機",
            .moduleStatusLoading: "読み込み中",
            .moduleStatusReady: "準備完了",
            .moduleStatusError: "エラー",
            .moduleLoad: "読み込む",
            .moduleUnload: "アンロード",
            .moduleLoadingOverlay: "読み込み中",
            .contextLengthTitle: "コンテキスト長",
            .contextLengthShort: "短い会話",
            .contextLengthMedium: "中程度の会話",
            .contextLengthLong: "長い会話",
            .contextLengthCustom: "カスタム",
            .contextLengthCustomPlaceholder: "トークン数を入力",
            .contextLengthCustomMessage: "範囲：100〜262143",
            .contextLengthCustomWarning: "コンテキストが短すぎる（<4K）と会話が早期に打ち切られ、良好な体験が得られません。\n\nコンテキストが長すぎる（>32K）とデバイスのハードウェアに過度な負荷がかかり、発熱、動作遅延、クラッシュが発生する可能性があります。\n\nご自身のニーズとデバイスの性能を考慮して適切な最大コンテキストを設定し、起こり得る悪影響を受け入れてください。",
            .contextLengthCustomWarningConfirm: "了解しました",
            .reasoningThinking: "思考",
            .reasoningDirect: "直接回答",
            .attachmentPickImage: "画像を選択",
            .composerPlaceholder: "メッセージを入力...",
            .renameTitle: "カスタムタイトル",
            .renamePlaceholder: "カスタムタイトルを入力",
            .commonCancel: "キャンセル",
            .commonSave: "保存",
            .renameMessage: "この会話に短いタイトルを設定します。",
            .historyCustomTitle: "カスタムタイトル",
            .historyAITitleGenerate: "AIタイトルを生成",
            .historyAITitleGenerating: "タイトルを生成中",
            .historyDeleteConversation: "会話を削除",
            .gallerySelectedImages: "送信前の画像",
            .galleryConversationImages: "会話の画像",
            .assistantStoppedThinking: "(ユーザーが私の思考を停止しました)",
            .attachmentImageProcessingWait: "（処理中です。しばらくお待ちください）",
            .attachmentImageProcessingStopped: "ユーザーが画像分析を停止しました。続けるには画像を再アップロードしてください。",
            .attachmentImageWarning: "現在のモデルは画像の理解能力が限られています。各画像は大量のコンテキストトークンを消費します。画像を添付すると、モデルは自動的に直接回答モードに切り替わります（思考機能は無効になります）。\n\nこれらの制限にご注意ください。",
            .attachmentImageWarningConfirm: "了解しました",
            .settingsThinkingMode: "思考モード",
            .thinkingModeEnabled: "有効",
            .thinkingModeDisabled: "無効",
            .thinkingModeWarning: "思考モードでは、モデルが回答前にステップごとに推論を行い、複雑な質問への回答品質を向上させることができます。\n\nただし、思考モードはトークン消費と生成時間を大幅に増加させます。ハードウェアが限られたデバイスでは、顕著な遅延や発熱が生じる可能性があります。\n\n品質のニーズとデバイスの性能をバランスよくご検討ください。",
            .thinkingModeWarningConfirm: "有効にする",
            .thinkingModeLockedHint: "思考モードは現在無効です。先に設定で有効にしてください。"
        ],
        .korean: [
            .settingsTitle: "설정",
            .settingsLanguage: "언어",
            .settingsAppearance: "테마",
            .settingsChatTitle: "채팅 제목",
            .settingsChatStyle: "채팅 스타일",
            .settingsLanguageAuto: "자동(%@)",
            .settingsDeleteHistory: "기록 전체 삭제",
            .settingsDeleteHistoryAction: "삭제",
            .settingsDeleteHistoryTitle: "기록 전체 삭제",
            .settingsDeleteHistoryMessage: "채팅 기록은 이 기기에만 저장됩니다. 모든 기록을 삭제하면 되돌릴 수 없습니다.\n\n(정말 되돌릴 수 없어요 😊~)\n\n모든 기록을 삭제할지 확인해 주세요.",
            .settingsDeleteHistoryConfirm: "삭제",
            .settingsRestoreDefaults: "기본 설정 복원",
            .settingsRestoreDefaultsAction: "복원",
            .settingsRestoreDefaultsTitle: "기본 설정 복원",
            .settingsRestoreDefaultsMessage: "언어 설정, 테마 색상, 채팅 제목 옵션, 채팅 스타일, 컨텍스트 길이 옵션을 기본값으로 복원합니다.\n\n이 작업은 되돌릴 수 없습니다.",
            .settingsRestoreDefaultsConfirm: "확인",
            .appearanceLight: "라이트",
            .appearanceDark: "다크",
            .appearanceSystem: "시스템 설정 따르기",
            .chatTitleModeContent: "기본 대화 내용을 제목으로 사용",
            .chatTitleModeAI: "AI가 새 채팅 제목 자동 생성",
            .chatStyleDefault: "기본",
            .chatStyleEfficiency: "효율",
            .chatStyleEnthusiasm: "열정",
            .chatStyleGentle: "부드러움",
            .chatStyleSerious: "진지함",
            .sidebarHistory: "로컬 대화 기록",
            .sidebarNewConversation: "새 채팅",
            .sidebarEmptyHistory: "아직 로컬 대화 기록이 없습니다",
            .sidebarSettings: "설정",
            .moduleStatusWaiting: "대기",
            .moduleStatusLoading: "불러오는 중",
            .moduleStatusReady: "준비 완료",
            .moduleStatusError: "오류",
            .moduleLoad: "불러오기",
            .moduleUnload: "언로드",
            .moduleLoadingOverlay: "불러오는 중",
            .contextLengthTitle: "컨텍스트 길이",
            .contextLengthShort: "짧은 대화",
            .contextLengthMedium: "중간 대화",
            .contextLengthLong: "긴 대화",
            .contextLengthCustom: "사용자 지정",
            .contextLengthCustomPlaceholder: "토큰 수 입력",
            .contextLengthCustomMessage: "범위: 100–262143",
            .contextLengthCustomWarning: "컨텍스트가 너무 짧으면(<4K) 대화가 조기에 중단되어 좋은 경험을 얻을 수 없습니다.\n\n컨텍스트가 너무 길면(>32K) 기기 하드웨어에 과도한 부담을 주어 발열, 지연 또는 앱 충돌이 발생할 수 있습니다.\n\n개인적인 필요와 기기 사양을 고려하여 적절한 최대 컨텍스트를 설정하고, 발생할 수 있는 부정적인 영향을 감수하시기 바랍니다.",
            .contextLengthCustomWarningConfirm: "확인했습니다",
            .reasoningThinking: "생각",
            .reasoningDirect: "직답",
            .attachmentPickImage: "이미지 선택",
            .composerPlaceholder: "메시지 입력...",
            .renameTitle: "사용자 지정 제목",
            .renamePlaceholder: "사용자 지정 제목 입력",
            .commonCancel: "취소",
            .commonSave: "저장",
            .renameMessage: "이 대화에 더 짧은 제목을 설정합니다.",
            .historyCustomTitle: "사용자 지정 제목",
            .historyAITitleGenerate: "AI 제목 생성",
            .historyAITitleGenerating: "제목 생성 중",
            .historyDeleteConversation: "대화 삭제",
            .gallerySelectedImages: "전송 전 이미지",
            .galleryConversationImages: "대화 이미지",
            .assistantStoppedThinking: "(사용자가 제 생각을 중지시켰습니다)",
            .attachmentImageProcessingWait: "（처리 중이니 잠시만 기다려 주세요）",
            .attachmentImageProcessingStopped: "사용자가 이미지 분석을 중지했습니다. 계속하려면 이미지를 다시 업로드해 주세요.",
            .attachmentImageWarning: "현재 모델은 이미지 이해 능력이 제한적입니다. 각 이미지는 상당한 양의 컨텍스트 토큰을 소비합니다. 이미지가 첨부되면 모델은 자동으로 직접 답변 모드로 전환됩니다(사고 기능이 비활성화됩니다).\n\n이러한 제한 사항에 유의해 주세요.",
            .attachmentImageWarningConfirm: "이해했습니다",
            .settingsThinkingMode: "사고 모드",
            .thinkingModeEnabled: "활성화됨",
            .thinkingModeDisabled: "비활성화됨",
            .thinkingModeWarning: "사고 모드는 모델이 답변 전에 단계별로 추론할 수 있게 하여, 복잡한 질문에 대한 응답 품질을 향상시킬 수 있습니다.\n\n하지만 사고 모드는 토큰 소비와 생성 시간을 크게 증가시킵니다. 하드웨어가 제한된 기기에서는 눈에 띄는 지연이나 발열이 발생할 수 있습니다.\n\n품질 요구와 기기 성능을 균형 있게 고려해 주세요.",
            .thinkingModeWarningConfirm: "활성화",
            .thinkingModeLockedHint: "사고 모드가 현재 비활성화되어 있습니다. 먼저 설정에서 활성화해 주세요."
        ],
        .french: [
            .settingsTitle: "Paramètres",
            .settingsLanguage: "Langue",
            .settingsAppearance: "Thème",
            .settingsChatTitle: "Titre du chat",
            .settingsChatStyle: "Style de chat",
            .settingsLanguageAuto: "Auto (%@)",
            .settingsDeleteHistory: "Supprimer l'historique",
            .settingsDeleteHistoryAction: "Supprimer",
            .settingsDeleteHistoryTitle: "Supprimer tout l'historique local",
            .settingsDeleteHistoryMessage: "L'historique des conversations est stocké uniquement sur cet appareil. La suppression de tout l'historique est irréversible.\n\n(C'est vraiment irréversible 😊~)\n\nVeuillez confirmer la suppression de tout l'historique.",
            .settingsDeleteHistoryConfirm: "Supprimer",
            .settingsRestoreDefaults: "Rétablir les paramètres par défaut",
            .settingsRestoreDefaultsAction: "Restaurer",
            .settingsRestoreDefaultsTitle: "Rétablir les paramètres par défaut",
            .settingsRestoreDefaultsMessage: "Rétablir la langue par défaut, le thème, l'option de titre du chat, le style de chat et la longueur de contexte.\n\nCette action est irréversible.",
            .settingsRestoreDefaultsConfirm: "Confirmer",
            .appearanceLight: "Clair",
            .appearanceDark: "Sombre",
            .appearanceSystem: "Suivre le système",
            .chatTitleModeContent: "Texte de conversation par défaut",
            .chatTitleModeAI: "Titre auto par IA pour les nouveaux chats",
            .chatStyleDefault: "Par défaut",
            .chatStyleEfficiency: "Efficace",
            .chatStyleEnthusiasm: "Chaleureux",
            .chatStyleGentle: "Doux",
            .chatStyleSerious: "Sérieux",
            .sidebarHistory: "Historique local des chats",
            .sidebarNewConversation: "Nouveau chat",
            .sidebarEmptyHistory: "Aucun historique local pour le moment",
            .sidebarSettings: "Paramètres",
            .moduleStatusWaiting: "En attente",
            .moduleStatusLoading: "Chargement",
            .moduleStatusReady: "Prêt",
            .moduleStatusError: "Erreur",
            .moduleLoad: "Charger",
            .moduleUnload: "Décharger",
            .moduleLoadingOverlay: "Chargement",
            .contextLengthTitle: "Longueur du contexte",
            .contextLengthShort: "Chat court",
            .contextLengthMedium: "Chat moyen",
            .contextLengthLong: "Chat long",
            .contextLengthCustom: "Personnalisé",
            .contextLengthCustomPlaceholder: "Entrez le nombre de tokens",
            .contextLengthCustomMessage: "Plage : 100–262143",
            .contextLengthCustomWarning: "Un contexte trop court (<4K) provoquera l'interruption prématurée des conversations, entraînant une mauvaise expérience.\n\nUn contexte trop long (>32K) exerce une pression excessive sur le matériel de l'appareil et peut provoquer une surchauffe, des ralentissements, voire des plantages.\n\nVeuillez équilibrer vos besoins personnels et les capacités de votre appareil pour définir un contexte maximum approprié, et acceptez les effets négatifs potentiels.",
            .contextLengthCustomWarningConfirm: "J'ai compris",
            .reasoningThinking: "Réflexion",
            .reasoningDirect: "Réponse directe",
            .attachmentPickImage: "Choisir des images",
            .composerPlaceholder: "Saisissez un message...",
            .renameTitle: "Titre personnalisé",
            .renamePlaceholder: "Saisissez un titre personnalisé",
            .commonCancel: "Annuler",
            .commonSave: "Enregistrer",
            .renameMessage: "Définissez un titre plus court pour cette conversation.",
            .historyCustomTitle: "Titre personnalisé",
            .historyAITitleGenerate: "Générer un titre IA",
            .historyAITitleGenerating: "Génération du titre",
            .historyDeleteConversation: "Supprimer la conversation",
            .gallerySelectedImages: "Images sélectionnées",
            .galleryConversationImages: "Images de la conversation",
            .assistantStoppedThinking: "(L'utilisateur a arrêté ma réflexion)",
            .attachmentImageProcessingWait: "(Traitement en cours, veuillez patienter)",
            .attachmentImageProcessingStopped: "L'utilisateur a arrêté l'analyse de l'image. Veuillez téléverser à nouveau l'image pour continuer.",
            .attachmentImageWarning: "Le modèle actuel a une compréhension limitée des images. Chaque image consomme une quantité importante de tokens de contexte. Lorsque des images sont jointes, le modèle passera automatiquement en mode réponse directe (la réflexion est désactivée).\n\nVeuillez tenir compte de ces limitations.",
            .attachmentImageWarningConfirm: "J'ai compris",
            .settingsThinkingMode: "Mode réflexion",
            .thinkingModeEnabled: "Activé",
            .thinkingModeDisabled: "Désactivé",
            .thinkingModeWarning: "Le mode réflexion permet au modèle de raisonner étape par étape avant de répondre, ce qui peut améliorer la qualité des réponses pour les questions complexes.\n\nCependant, le mode réflexion augmente considérablement la consommation de tokens et le temps de génération. Sur les appareils à capacités matérielles limitées, cela peut provoquer des ralentissements ou une surchauffe notables.\n\nVeuillez équilibrer vos besoins de qualité et les capacités de votre appareil.",
            .thinkingModeWarningConfirm: "Activer",
            .thinkingModeLockedHint: "Le mode réflexion est actuellement désactivé. Veuillez d'abord l'activer dans les réglages."
        ],
        .german: [
            .settingsTitle: "Einstellungen",
            .settingsLanguage: "Sprache",
            .settingsAppearance: "Thema",
            .settingsChatTitle: "Chat-Titel",
            .settingsChatStyle: "Chatstil",
            .settingsLanguageAuto: "Automatisch (%@)",
            .settingsDeleteHistory: "Verlauf löschen",
            .settingsDeleteHistoryAction: "Löschen",
            .settingsDeleteHistoryTitle: "Gesamten lokalen Verlauf löschen",
            .settingsDeleteHistoryMessage: "Der Chatverlauf wird nur auf diesem Gerät gespeichert. Das Löschen des gesamten Verlaufs kann nicht rückgängig gemacht werden.\n\n(Das ist wirklich nicht rückgängig zu machen 😊~)\n\nBitte bestätigen Sie, dass Sie den gesamten Verlauf löschen möchten.",
            .settingsDeleteHistoryConfirm: "Löschen",
            .settingsRestoreDefaults: "Standardeinstellungen wiederherstellen",
            .settingsRestoreDefaultsAction: "Wiederherstellen",
            .settingsRestoreDefaultsTitle: "Standardeinstellungen wiederherstellen",
            .settingsRestoreDefaultsMessage: "Die Standardwerte für Sprache, Designfarbe, Chat-Titeloption, Chatstil und Kontextlänge wiederherstellen.\n\nDieser Vorgang kann nicht rückgängig gemacht werden.",
            .settingsRestoreDefaultsConfirm: "Bestätigen",
            .appearanceLight: "Hell",
            .appearanceDark: "Dunkel",
            .appearanceSystem: "System folgen",
            .chatTitleModeContent: "Standard-Chatinhalt als Titel",
            .chatTitleModeAI: "KI-Titel für neue Chats automatisch",
            .chatStyleDefault: "Standard",
            .chatStyleEfficiency: "Effizient",
            .chatStyleEnthusiasm: "Herzlich",
            .chatStyleGentle: "Sanft",
            .chatStyleSerious: "Ernst",
            .sidebarHistory: "Lokaler Chatverlauf",
            .sidebarNewConversation: "Neuer Chat",
            .sidebarEmptyHistory: "Noch kein lokaler Chatverlauf",
            .sidebarSettings: "Einstellungen",
            .moduleStatusWaiting: "Warten",
            .moduleStatusLoading: "Laden",
            .moduleStatusReady: "Bereit",
            .moduleStatusError: "Fehler",
            .moduleLoad: "Laden",
            .moduleUnload: "Entladen",
            .moduleLoadingOverlay: "Wird geladen",
            .contextLengthTitle: "Kontextlänge",
            .contextLengthShort: "Kurzer Chat",
            .contextLengthMedium: "Mittlerer Chat",
            .contextLengthLong: "Langer Chat",
            .contextLengthCustom: "Benutzerdefiniert",
            .contextLengthCustomPlaceholder: "Token-Anzahl eingeben",
            .contextLengthCustomMessage: "Bereich: 100–262143",
            .contextLengthCustomWarning: "Ein zu kurzer Kontext (<4K) führt dazu, dass Gespräche vorzeitig abgebrochen werden, was zu einem schlechten Erlebnis führt.\n\nEin zu langer Kontext (>32K) belastet die Hardware des Geräts übermäßig und kann Überhitzung, Verzögerungen oder Abstürze verursachen.\n\nBitte wägen Sie Ihre persönlichen Bedürfnisse und die Leistungsfähigkeit Ihres Geräts ab, um einen geeigneten maximalen Kontext festzulegen, und akzeptieren Sie mögliche negative Auswirkungen.",
            .contextLengthCustomWarningConfirm: "Verstanden",
            .reasoningThinking: "Denken",
            .reasoningDirect: "Direkt",
            .attachmentPickImage: "Bilder wählen",
            .composerPlaceholder: "Nachricht eingeben...",
            .renameTitle: "Benutzerdefinierter Titel",
            .renamePlaceholder: "Benutzerdefinierten Titel eingeben",
            .commonCancel: "Abbrechen",
            .commonSave: "Speichern",
            .renameMessage: "Einen kürzeren Titel für diese Unterhaltung festlegen.",
            .historyCustomTitle: "Benutzerdefinierter Titel",
            .historyAITitleGenerate: "KI-Titel erzeugen",
            .historyAITitleGenerating: "Titel wird erzeugt",
            .historyDeleteConversation: "Unterhaltung löschen",
            .gallerySelectedImages: "Ausgewählte Bilder",
            .galleryConversationImages: "Unterhaltungsbilder",
            .assistantStoppedThinking: "(Der Benutzer hat mein Nachdenken gestoppt)",
            .attachmentImageProcessingWait: "(Verarbeitung läuft, bitte warten)",
            .attachmentImageProcessingStopped: "Der Benutzer hat die Bildanalyse gestoppt. Bitte laden Sie das Bild erneut hoch, wenn Sie fortfahren möchten.",
            .attachmentImageWarning: "Das aktuelle Modell hat ein begrenztes Bildverständnis. Jedes Bild verbraucht eine erhebliche Menge an Kontext-Tokens. Wenn Bilder angehängt sind, wechselt das Modell automatisch in den Direktantwort-Modus (Denken wird deaktiviert).\n\nBitte beachten Sie diese Einschränkungen.",
            .attachmentImageWarningConfirm: "Verstanden",
            .settingsThinkingMode: "Denkmodus",
            .thinkingModeEnabled: "Aktiviert",
            .thinkingModeDisabled: "Deaktiviert",
            .thinkingModeWarning: "Der Denkmodus ermöglicht dem Modell, vor der Antwort schrittweise zu schlussfolgern, was die Antwortqualität bei komplexen Fragen verbessern kann.\n\nAllerdings erhöht der Denkmodus den Token-Verbrauch und die Generierungszeit erheblich. Auf Geräten mit begrenzter Hardware kann es zu spürbaren Verzögerungen oder Überhitzung kommen.\n\nBitte wägen Sie Qualitätsanforderungen und Geräteleistung ab.",
            .thinkingModeWarningConfirm: "Aktivieren",
            .thinkingModeLockedHint: "Der Denkmodus ist derzeit deaktiviert. Bitte aktivieren Sie ihn zuerst in den Einstellungen."
        ],
        .spanish: [
            .settingsTitle: "Configuración",
            .settingsLanguage: "Idioma",
            .settingsAppearance: "Tema",
            .settingsChatTitle: "Título del chat",
            .settingsChatStyle: "Estilo de chat",
            .settingsLanguageAuto: "Automático (%@)",
            .settingsDeleteHistory: "Eliminar historial",
            .settingsDeleteHistoryAction: "Eliminar",
            .settingsDeleteHistoryTitle: "Eliminar todo el historial local",
            .settingsDeleteHistoryMessage: "El historial de chat solo se almacena en este dispositivo. Eliminar todo el historial no se puede deshacer.\n\n(De verdad no se puede deshacer 😊~)\n\nConfirma si deseas eliminar todo el historial.",
            .settingsDeleteHistoryConfirm: "Eliminar",
            .settingsRestoreDefaults: "Restaurar ajustes predeterminados",
            .settingsRestoreDefaultsAction: "Restaurar",
            .settingsRestoreDefaultsTitle: "Restaurar ajustes predeterminados",
            .settingsRestoreDefaultsMessage: "Restaurar la configuración predeterminada de idioma, tema, opción de título del chat, estilo de chat y longitud de contexto.\n\nEsta acción no se puede deshacer.",
            .settingsRestoreDefaultsConfirm: "Confirmar",
            .appearanceLight: "Claro",
            .appearanceDark: "Oscuro",
            .appearanceSystem: "Seguir sistema",
            .chatTitleModeContent: "Contenido de chat como título",
            .chatTitleModeAI: "IA genera títulos para nuevos chats",
            .chatStyleDefault: "Predeterminado",
            .chatStyleEfficiency: "Eficiente",
            .chatStyleEnthusiasm: "Entusiasta",
            .chatStyleGentle: "Suave",
            .chatStyleSerious: "Serio",
            .sidebarHistory: "Historial local de chats",
            .sidebarNewConversation: "Nuevo chat",
            .sidebarEmptyHistory: "Aún no hay historial local",
            .sidebarSettings: "Configuración",
            .moduleStatusWaiting: "En espera",
            .moduleStatusLoading: "Cargando",
            .moduleStatusReady: "Listo",
            .moduleStatusError: "Error",
            .moduleLoad: "Cargar",
            .moduleUnload: "Descargar",
            .moduleLoadingOverlay: "Cargando",
            .contextLengthTitle: "Longitud de contexto",
            .contextLengthShort: "Chat corto",
            .contextLengthMedium: "Chat medio",
            .contextLengthLong: "Chat largo",
            .contextLengthCustom: "Personalizado",
            .contextLengthCustomPlaceholder: "Ingrese cantidad de tokens",
            .contextLengthCustomMessage: "Rango: 100–262143",
            .contextLengthCustomWarning: "Un contexto demasiado corto (<4K) hará que las conversaciones se interrumpan prematuramente, lo que resultará en una mala experiencia.\n\nUn contexto demasiado largo (>32K) ejerce una presión excesiva sobre el hardware del dispositivo y puede causar sobrecalentamiento, retrasos o cierres inesperados.\n\nPor favor, equilibre sus necesidades personales y las capacidades de su dispositivo al configurar el contexto máximo, y acepte los posibles efectos negativos.",
            .contextLengthCustomWarningConfirm: "Entendido",
            .reasoningThinking: "Pensar",
            .reasoningDirect: "Directa",
            .attachmentPickImage: "Seleccionar imágenes",
            .composerPlaceholder: "Escribe un mensaje...",
            .renameTitle: "Título personalizado",
            .renamePlaceholder: "Introduce un título personalizado",
            .commonCancel: "Cancelar",
            .commonSave: "Guardar",
            .renameMessage: "Define un título más corto para esta conversación.",
            .historyCustomTitle: "Título personalizado",
            .historyAITitleGenerate: "Generar título con IA",
            .historyAITitleGenerating: "Generando título",
            .historyDeleteConversation: "Eliminar conversación",
            .gallerySelectedImages: "Imágenes seleccionadas",
            .galleryConversationImages: "Imágenes de la conversación",
            .assistantStoppedThinking: "(El usuario ha detenido mi razonamiento)",
            .attachmentImageProcessingWait: "(Procesando, por favor espera con paciencia)",
            .attachmentImageProcessingStopped: "El usuario ha detenido el análisis de la imagen. Si deseas continuar, vuelve a subirla.",
            .attachmentImageWarning: "El modelo actual tiene una capacidad limitada para comprender imágenes. Cada imagen consume una cantidad significativa de tokens de contexto. Cuando se adjuntan imágenes, el modelo cambiará automáticamente al modo de respuesta directa (el pensamiento se desactiva).\n\nPor favor, tenga en cuenta estas limitaciones.",
            .attachmentImageWarningConfirm: "Entendido",
            .settingsThinkingMode: "Modo pensamiento",
            .thinkingModeEnabled: "Activado",
            .thinkingModeDisabled: "Desactivado",
            .thinkingModeWarning: "El modo pensamiento permite al modelo razonar paso a paso antes de responder, lo que puede mejorar la calidad de las respuestas para preguntas complejas.\n\nSin embargo, el modo pensamiento aumenta significativamente el consumo de tokens y el tiempo de generación. En dispositivos con hardware limitado, puede causar retrasos notables o sobrecalentamiento.\n\nPor favor, equilibre las necesidades de calidad y las capacidades del dispositivo.",
            .thinkingModeWarningConfirm: "Activar",
            .thinkingModeLockedHint: "El modo pensamiento está actualmente desactivado. Por favor, actívelo primero en Configuración."
        ],
        .portuguese: [
            .settingsTitle: "Configurações",
            .settingsLanguage: "Idioma",
            .settingsAppearance: "Tema",
            .settingsChatTitle: "Título do chat",
            .settingsChatStyle: "Estilo de chat",
            .settingsLanguageAuto: "Automático (%@)",
            .settingsDeleteHistory: "Excluir histórico",
            .settingsDeleteHistoryAction: "Excluir",
            .settingsDeleteHistoryTitle: "Excluir todo o histórico local",
            .settingsDeleteHistoryMessage: "O histórico de conversa é armazenado apenas neste dispositivo. Excluir todo o histórico não pode ser desfeito.\n\n(Isso realmente não pode ser desfeito 😊~)\n\nConfirme se deseja excluir todo o histórico.",
            .settingsDeleteHistoryConfirm: "Excluir",
            .settingsRestoreDefaults: "Restaurar padrões",
            .settingsRestoreDefaultsAction: "Restaurar",
            .settingsRestoreDefaultsTitle: "Restaurar configurações padrão",
            .settingsRestoreDefaultsMessage: "Restaurar as configurações padrão de idioma, tema, opção de título do chat, estilo de chat e comprimento do contexto.\n\nEsta ação não pode ser desfeita.",
            .settingsRestoreDefaultsConfirm: "Confirmar",
            .appearanceLight: "Claro",
            .appearanceDark: "Escuro",
            .appearanceSystem: "Seguir o sistema",
            .chatTitleModeContent: "Conteúdo da conversa como título",
            .chatTitleModeAI: "IA gera títulos para novos chats",
            .chatStyleDefault: "Padrão",
            .chatStyleEfficiency: "Eficiente",
            .chatStyleEnthusiasm: "Entusiasmado",
            .chatStyleGentle: "Gentil",
            .chatStyleSerious: "Sério",
            .sidebarHistory: "Histórico local de conversas",
            .sidebarNewConversation: "Nova conversa",
            .sidebarEmptyHistory: "Ainda não há histórico local",
            .sidebarSettings: "Configurações",
            .moduleStatusWaiting: "Aguardando",
            .moduleStatusLoading: "Carregando",
            .moduleStatusReady: "Pronto",
            .moduleStatusError: "Erro",
            .moduleLoad: "Carregar",
            .moduleUnload: "Descarregar",
            .moduleLoadingOverlay: "Carregando",
            .contextLengthTitle: "Comprimento do contexto",
            .contextLengthShort: "Conversa curta",
            .contextLengthMedium: "Conversa média",
            .contextLengthLong: "Conversa longa",
            .contextLengthCustom: "Personalizado",
            .contextLengthCustomPlaceholder: "Digite a quantidade de tokens",
            .contextLengthCustomMessage: "Intervalo: 100–262143",
            .contextLengthCustomWarning: "Um contexto muito curto (<4K) fará com que as conversas sejam interrompidas prematuramente, resultando em uma experiência ruim.\n\nUm contexto muito longo (>32K) exerce pressão excessiva no hardware do dispositivo e pode causar superaquecimento, lentidão ou travamentos.\n\nPor favor, equilibre suas necessidades pessoais e as capacidades do seu dispositivo ao definir o contexto máximo, e aceite os possíveis efeitos negativos.",
            .contextLengthCustomWarningConfirm: "Entendi",
            .reasoningThinking: "Pensando",
            .reasoningDirect: "Direta",
            .attachmentPickImage: "Selecionar imagens",
            .composerPlaceholder: "Digite uma mensagem...",
            .renameTitle: "Título personalizado",
            .renamePlaceholder: "Digite um título personalizado",
            .commonCancel: "Cancelar",
            .commonSave: "Salvar",
            .renameMessage: "Defina um título mais curto para esta conversa.",
            .historyCustomTitle: "Título personalizado",
            .historyAITitleGenerate: "Gerar título com IA",
            .historyAITitleGenerating: "Gerando título",
            .historyDeleteConversation: "Excluir conversa",
            .gallerySelectedImages: "Imagens selecionadas",
            .galleryConversationImages: "Imagens da conversa",
            .assistantStoppedThinking: "(O usuário interrompeu meu raciocínio)",
            .attachmentImageProcessingWait: "(Processando, por favor aguarde com paciência)",
            .attachmentImageProcessingStopped: "O usuário interrompeu a análise da imagem. Se quiser continuar, envie a imagem novamente.",
            .attachmentImageWarning: "O modelo atual tem capacidade limitada de compreensão de imagens. Cada imagem consome uma quantidade significativa de tokens de contexto. Quando imagens são anexadas, o modelo mudará automaticamente para o modo de resposta direta (o pensamento é desativado).\n\nPor favor, esteja atento a essas limitações.",
            .attachmentImageWarningConfirm: "Entendi",
            .settingsThinkingMode: "Modo pensamento",
            .thinkingModeEnabled: "Ativado",
            .thinkingModeDisabled: "Desativado",
            .thinkingModeWarning: "O modo pensamento permite que o modelo raciocine passo a passo antes de responder, o que pode melhorar a qualidade das respostas para perguntas complexas.\n\nNo entanto, o modo pensamento aumenta significativamente o consumo de tokens e o tempo de geração. Em dispositivos com hardware limitado, pode causar atrasos perceptíveis ou superaquecimento.\n\nPor favor, equilibre as necessidades de qualidade e as capacidades do dispositivo.",
            .thinkingModeWarningConfirm: "Ativar",
            .thinkingModeLockedHint: "O modo pensamento está atualmente desativado. Por favor, ative-o primeiro nas Configurações."
        ],
        .russian: [
            .settingsTitle: "Настройки",
            .settingsLanguage: "Язык",
            .settingsAppearance: "Тема",
            .settingsChatTitle: "Заголовок чата",
            .settingsChatStyle: "Стиль чата",
            .settingsLanguageAuto: "Авто (%@)",
            .settingsDeleteHistory: "Удалить историю",
            .settingsDeleteHistoryAction: "Удалить",
            .settingsDeleteHistoryTitle: "Удалить всю локальную историю",
            .settingsDeleteHistoryMessage: "История чатов хранится только на этом устройстве. Удаление всей истории нельзя отменить.\n\n(Это действительно нельзя отменить 😊~)\n\nПодтвердите удаление всей истории.",
            .settingsDeleteHistoryConfirm: "Удалить",
            .settingsRestoreDefaults: "Восстановить настройки по умолчанию",
            .settingsRestoreDefaultsAction: "Сбросить",
            .settingsRestoreDefaultsTitle: "Восстановить настройки по умолчанию",
            .settingsRestoreDefaultsMessage: "Восстановить значения по умолчанию для языка, темы, параметра заголовка чата, стиля чата и длины контекста.\n\nЭто действие нельзя отменить.",
            .settingsRestoreDefaultsConfirm: "Подтвердить",
            .appearanceLight: "Светлая",
            .appearanceDark: "Тёмная",
            .appearanceSystem: "Как в системе",
            .chatTitleModeContent: "Текст диалога как заголовок",
            .chatTitleModeAI: "ИИ создаёт заголовки для новых чатов",
            .chatStyleDefault: "По умолчанию",
            .chatStyleEfficiency: "Эффективный",
            .chatStyleEnthusiasm: "Воодушевлённый",
            .chatStyleGentle: "Мягкий",
            .chatStyleSerious: "Серьёзный",
            .sidebarHistory: "Локальная история чатов",
            .sidebarNewConversation: "Новый чат",
            .sidebarEmptyHistory: "Локальной истории пока нет",
            .sidebarSettings: "Настройки",
            .moduleStatusWaiting: "Ожидание",
            .moduleStatusLoading: "Загрузка",
            .moduleStatusReady: "Готово",
            .moduleStatusError: "Ошибка",
            .moduleLoad: "Загрузить",
            .moduleUnload: "Выгрузить",
            .moduleLoadingOverlay: "Загрузка",
            .contextLengthTitle: "Длина контекста",
            .contextLengthShort: "Короткий чат",
            .contextLengthMedium: "Средний чат",
            .contextLengthLong: "Длинный чат",
            .contextLengthCustom: "Пользовательский",
            .contextLengthCustomPlaceholder: "Введите количество токенов",
            .contextLengthCustomMessage: "Диапазон: 100–262143",
            .contextLengthCustomWarning: "Слишком короткий контекст (<4K) приведёт к преждевременному прерыванию разговоров, что ухудшит опыт использования.\n\nСлишком длинный контекст (>32K) создаёт чрезмерную нагрузку на аппаратное обеспечение устройства и может вызвать перегрев, задержки или вылеты приложения.\n\nПожалуйста, учитывайте свои потребности и возможности устройства при настройке максимального контекста и примите возможные негативные последствия.",
            .contextLengthCustomWarningConfirm: "Понятно",
            .reasoningThinking: "Размышление",
            .reasoningDirect: "Прямой ответ",
            .attachmentPickImage: "Выбрать изображения",
            .composerPlaceholder: "Введите сообщение...",
            .renameTitle: "Пользовательский заголовок",
            .renamePlaceholder: "Введите пользовательский заголовок",
            .commonCancel: "Отмена",
            .commonSave: "Сохранить",
            .renameMessage: "Задайте более короткий заголовок для этого диалога.",
            .historyCustomTitle: "Пользовательский заголовок",
            .historyAITitleGenerate: "Создать заголовок ИИ",
            .historyAITitleGenerating: "Заголовок создаётся",
            .historyDeleteConversation: "Удалить чат",
            .gallerySelectedImages: "Выбранные изображения",
            .galleryConversationImages: "Изображения диалога",
            .assistantStoppedThinking: "(Пользователь остановил мои размышления)",
            .attachmentImageProcessingWait: "(Идёт обработка, пожалуйста, подождите)",
            .attachmentImageProcessingStopped: "Пользователь остановил анализ изображения. Чтобы продолжить, загрузите изображение заново.",
            .attachmentImageWarning: "Текущая модель имеет ограниченные возможности понимания изображений. Каждое изображение потребляет значительное количество контекстных токенов. При прикреплении изображений модель автоматически переключится в режим прямого ответа (мышление отключается).\n\nПожалуйста, учитывайте эти ограничения.",
            .attachmentImageWarningConfirm: "Понятно",
            .settingsThinkingMode: "Режим мышления",
            .thinkingModeEnabled: "Включён",
            .thinkingModeDisabled: "Выключен",
            .thinkingModeWarning: "Режим мышления позволяет модели рассуждать пошагово перед ответом, что может повысить качество ответов на сложные вопросы.\n\nОднако режим мышления значительно увеличивает потребление токенов и время генерации. На устройствах с ограниченными аппаратными возможностями это может вызвать заметные задержки или перегрев.\n\nПожалуйста, сбалансируйте потребности в качестве и возможности устройства.",
            .thinkingModeWarningConfirm: "Включить",
            .thinkingModeLockedHint: "Режим мышления в настоящее время отключён. Пожалуйста, сначала включите его в настройках."
        ],
        .arabic: [
            .settingsTitle: "الإعدادات",
            .settingsLanguage: "اللغة",
            .settingsAppearance: "المظهر",
            .settingsChatTitle: "عنوان الدردشة",
            .settingsChatStyle: "أسلوب الدردشة",
            .settingsLanguageAuto: "تلقائي (%@)",
            .settingsDeleteHistory: "حذف السجل",
            .settingsDeleteHistoryAction: "حذف",
            .settingsDeleteHistoryTitle: "حذف كل السجل المحلي",
            .settingsDeleteHistoryMessage: "يتم حفظ سجل المحادثات على هذا الجهاز فقط. حذف كل السجل لا يمكن التراجع عنه.\n\n(لا يمكن التراجع عنه فعلًا 😊~)\n\nيرجى تأكيد حذف كل السجل.",
            .settingsDeleteHistoryConfirm: "حذف",
            .settingsRestoreDefaults: "استعادة الإعدادات الافتراضية",
            .settingsRestoreDefaultsAction: "استعادة",
            .settingsRestoreDefaultsTitle: "استعادة الإعدادات الافتراضية",
            .settingsRestoreDefaultsMessage: "استعادة الإعدادات الافتراضية للغة ولون السمة وخيار عنوان الدردشة وأسلوب الدردشة وطول السياق.\n\nلا يمكن التراجع عن هذا الإجراء.",
            .settingsRestoreDefaultsConfirm: "تأكيد",
            .appearanceLight: "فاتح",
            .appearanceDark: "داكن",
            .appearanceSystem: "اتباع النظام",
            .chatTitleModeContent: "نص المحادثة كعنوان",
            .chatTitleModeAI: "إنشاء عناوين تلقائية للمحادثات الجديدة",
            .chatStyleDefault: "افتراضي",
            .chatStyleEfficiency: "فعّال",
            .chatStyleEnthusiasm: "حماسي",
            .chatStyleGentle: "لطيف",
            .chatStyleSerious: "جاد",
            .sidebarHistory: "سجل الدردشة المحلي",
            .sidebarNewConversation: "دردشة جديدة",
            .sidebarEmptyHistory: "لا يوجد سجل محلي بعد",
            .sidebarSettings: "الإعدادات",
            .moduleStatusWaiting: "انتظار",
            .moduleStatusLoading: "جارٍ التحميل",
            .moduleStatusReady: "جاهز",
            .moduleStatusError: "خطأ",
            .moduleLoad: "تحميل",
            .moduleUnload: "إلغاء التحميل",
            .moduleLoadingOverlay: "جارٍ التحميل",
            .contextLengthTitle: "طول السياق",
            .contextLengthShort: "دردشة قصيرة",
            .contextLengthMedium: "دردشة متوسطة",
            .contextLengthLong: "دردشة طويلة",
            .contextLengthCustom: "مخصص",
            .contextLengthCustomPlaceholder: "أدخل عدد الرموز",
            .contextLengthCustomMessage: "النطاق: 100–262143",
            .contextLengthCustomWarning: "السياق القصير جدًا (<4K) سيؤدي إلى قطع المحادثات مبكرًا، مما يؤدي إلى تجربة سيئة.\n\nالسياق الطويل جدًا (>32K) يضع ضغطًا مفرطًا على أجهزة الجهاز وقد يتسبب في ارتفاع الحرارة أو التأخير أو إغلاق التطبيق بشكل مفاجئ.\n\nيرجى الموازنة بين احتياجاتك الشخصية وقدرات جهازك عند تعيين الحد الأقصى للسياق، وقبول أي آثار سلبية محتملة.",
            .contextLengthCustomWarningConfirm: "فهمت",
            .reasoningThinking: "تفكير",
            .reasoningDirect: "مباشر",
            .attachmentPickImage: "اختيار الصور",
            .composerPlaceholder: "اكتب رسالة...",
            .renameTitle: "عنوان مخصص",
            .renamePlaceholder: "أدخل عنوانًا مخصصًا",
            .commonCancel: "إلغاء",
            .commonSave: "حفظ",
            .renameMessage: "عيّن عنوانًا أقصر لهذه المحادثة.",
            .historyCustomTitle: "عنوان مخصص",
            .historyAITitleGenerate: "إنشاء عنوان بالذكاء الاصطناعي",
            .historyAITitleGenerating: "جارٍ إنشاء العنوان",
            .historyDeleteConversation: "حذف المحادثة",
            .gallerySelectedImages: "الصور المحددة",
            .galleryConversationImages: "صور المحادثة",
            .assistantStoppedThinking: "(أوقف المستخدم تفكيري)",
            .attachmentImageProcessingWait: "(جارٍ المعالجة، يُرجى التحلي بالصبر)",
            .attachmentImageProcessingStopped: "أوقف المستخدم تحليلي للصورة. إذا أردت المتابعة، يُرجى إعادة رفعها.",
            .attachmentImageWarning: "النموذج الحالي لديه قدرة محدودة على فهم الصور. كل صورة تستهلك كمية كبيرة من رموز السياق. عند إرفاق صور، سينتقل النموذج تلقائيًا إلى وضع الإجابة المباشرة (يتم تعطيل التفكير).\n\nيرجى مراعاة هذه القيود.",
            .attachmentImageWarningConfirm: "فهمت",
            .settingsThinkingMode: "وضع التفكير",
            .thinkingModeEnabled: "مُفعّل",
            .thinkingModeDisabled: "مُعطّل",
            .thinkingModeWarning: "يسمح وضع التفكير للنموذج بالتفكير خطوة بخطوة قبل الإجابة، مما قد يحسن جودة الإجابات للأسئلة المعقدة.\n\nومع ذلك، يزيد وضع التفكير بشكل كبير من استهلاك الرموز ووقت التوليد. على الأجهزة ذات الإمكانيات المحدودة، قد يسبب تأخرًا ملحوظًا أو ارتفاعًا في الحرارة.\n\nيرجى الموازنة بين احتياجات الجودة وقدرات الجهاز.",
            .thinkingModeWarningConfirm: "تفعيل",
            .thinkingModeLockedHint: "وضع التفكير معطّل حاليًا. يرجى تفعيله أولاً من الإعدادات."
        ],
        .hindi: [
            .settingsTitle: "सेटिंग्स",
            .settingsLanguage: "भाषा",
            .settingsAppearance: "थीम",
            .settingsChatTitle: "चैट शीर्षक",
            .settingsChatStyle: "चैट शैली",
            .settingsLanguageAuto: "ऑटो (%@)",
            .settingsDeleteHistory: "इतिहास हटाएं",
            .settingsDeleteHistoryAction: "हटाएं",
            .settingsDeleteHistoryTitle: "सारा स्थानीय इतिहास हटाएं",
            .settingsDeleteHistoryMessage: "चैट इतिहास केवल इसी डिवाइस पर संग्रहीत है। सारा इतिहास हटाने के बाद उसे वापस नहीं लाया जा सकता।\n\n(सच में वापस नहीं लाया जा सकता 😊~)\n\nकृपया पुष्टि करें कि आप सारा इतिहास हटाना चाहते हैं।",
            .settingsDeleteHistoryConfirm: "हटाएं",
            .settingsRestoreDefaults: "डिफ़ॉल्ट सेटिंग्स बहाल करें",
            .settingsRestoreDefaultsAction: "बहाल करें",
            .settingsRestoreDefaultsTitle: "डिफ़ॉल्ट सेटिंग्स बहाल करें",
            .settingsRestoreDefaultsMessage: "भाषा, थीम रंग, चैट शीर्षक विकल्प, चैट शैली और कॉन्टेक्स्ट लंबाई को डिफ़ॉल्ट पर बहाल करें।\n\nयह कार्रवाई वापस नहीं की जा सकती।",
            .settingsRestoreDefaultsConfirm: "पुष्टि करें",
            .appearanceLight: "हल्का",
            .appearanceDark: "गहरा",
            .appearanceSystem: "सिस्टम के अनुसार",
            .chatTitleModeContent: "डिफ़ॉल्ट चैट सामग्री को शीर्षक बनाएं",
            .chatTitleModeAI: "AI नई चैट के लिए स्वतः शीर्षक बनाए",
            .chatStyleDefault: "डिफ़ॉल्ट",
            .chatStyleEfficiency: "दक्ष",
            .chatStyleEnthusiasm: "उत्साही",
            .chatStyleGentle: "सौम्य",
            .chatStyleSerious: "गंभीर",
            .sidebarHistory: "स्थानीय चैट इतिहास",
            .sidebarNewConversation: "नई चैट",
            .sidebarEmptyHistory: "अभी कोई स्थानीय इतिहास नहीं है",
            .sidebarSettings: "सेटिंग्स",
            .moduleStatusWaiting: "प्रतीक्षा",
            .moduleStatusLoading: "लोड हो रहा है",
            .moduleStatusReady: "तैयार",
            .moduleStatusError: "त्रुटि",
            .moduleLoad: "लोड करें",
            .moduleUnload: "अनलोड करें",
            .moduleLoadingOverlay: "लोड हो रहा है",
            .contextLengthTitle: "कॉन्टेक्स्ट लंबाई",
            .contextLengthShort: "छोटी चैट",
            .contextLengthMedium: "मध्यम चैट",
            .contextLengthLong: "लंबी चैट",
            .contextLengthCustom: "कस्टम",
            .contextLengthCustomPlaceholder: "टोकन संख्या दर्ज करें",
            .contextLengthCustomMessage: "सीमा: 100–262143",
            .contextLengthCustomWarning: "बहुत छोटा कॉन्टेक्स्ट (<4K) बातचीत को समय से पहले काट देगा, जिससे अनुभव खराब होगा।\n\nबहुत लंबा कॉन्टेक्स्ट (>32K) डिवाइस के हार्डवेयर पर अत्यधिक दबाव डालता है और गर्मी, धीमापन या ऐप क्रैश हो सकता है।\n\nकृपया अपनी व्यक्तिगत ज़रूरतों और डिवाइस की क्षमताओं को संतुलित करते हुए उचित अधिकतम कॉन्टेक्स्ट सेट करें, और संभावित नकारात्मक प्रभावों को स्वीकार करें।",
            .contextLengthCustomWarningConfirm: "मैं समझता/समझती हूँ",
            .reasoningThinking: "सोच",
            .reasoningDirect: "सीधा",
            .attachmentPickImage: "चित्र चुनें",
            .composerPlaceholder: "संदेश लिखें...",
            .renameTitle: "कस्टम शीर्षक",
            .renamePlaceholder: "कस्टम शीर्षक दर्ज करें",
            .commonCancel: "रद्द करें",
            .commonSave: "सहेजें",
            .renameMessage: "इस बातचीत के लिए एक छोटा शीर्षक सेट करें।",
            .historyCustomTitle: "कस्टम शीर्षक",
            .historyAITitleGenerate: "AI शीर्षक बनाएं",
            .historyAITitleGenerating: "शीर्षक बन रहा है",
            .historyDeleteConversation: "बातचीत हटाएँ",
            .gallerySelectedImages: "चयनित चित्र",
            .galleryConversationImages: "बातचीत की तस्वीरें",
            .assistantStoppedThinking: "(उपयोगकर्ता ने मुझे सोचना बंद कराया)",
            .attachmentImageProcessingWait: "(प्रसंस्करण जारी है, कृपया धैर्य रखें)",
            .attachmentImageProcessingStopped: "उपयोगकर्ता ने मुझे छवि का विश्लेषण करने से रोक दिया है। आगे जारी रखने के लिए कृपया छवि फिर से अपलोड करें।",
            .attachmentImageWarning: "वर्तमान मॉडल की छवि समझने की क्षमता सीमित है। प्रत्येक छवि बड़ी मात्रा में संदर्भ टोकन का उपभोग करती है। जब छवियाँ संलग्न होती हैं, तो मॉडल स्वचालित रूप से प्रत्यक्ष उत्तर मोड में बदल जाएगा (सोच अक्षम हो जाती है)।\n\nकृपया इन सीमाओं का ध्यान रखें।",
            .attachmentImageWarningConfirm: "समझ गया",
            .settingsThinkingMode: "सोच मोड",
            .thinkingModeEnabled: "सक्षम",
            .thinkingModeDisabled: "अक्षम",
            .thinkingModeWarning: "सोच मोड मॉडल को उत्तर देने से पहले चरण-दर-चरण तर्क करने की अनुमति देता है, जो जटिल प्रश्नों के लिए उत्तर गुणवत्ता में सुधार कर सकता है।\n\nहालांकि, सोच मोड टोकन खपत और उत्पादन समय को काफी बढ़ा देता है। सीमित हार्डवेयर वाले उपकरणों पर, यह ध्यान देने योग्य देरी या अत्यधिक गर्मी का कारण बन सकता है।\n\nकृपया गुणवत्ता आवश्यकताओं और डिवाइस क्षमताओं को संतुलित करें।",
            .thinkingModeWarningConfirm: "सक्षम करें",
            .thinkingModeLockedHint: "सोच मोड वर्तमान में अक्षम है। कृपया पहले इसे सेटिंग्स में सक्षम करें।"
        ],
        .italian: [
            .settingsTitle: "Impostazioni",
            .settingsLanguage: "Lingua",
            .settingsAppearance: "Tema",
            .settingsChatTitle: "Titolo chat",
            .settingsChatStyle: "Stile chat",
            .settingsLanguageAuto: "Automatico (%@)",
            .settingsDeleteHistory: "Elimina cronologia",
            .settingsDeleteHistoryAction: "Elimina",
            .settingsDeleteHistoryTitle: "Elimina tutta la cronologia locale",
            .settingsDeleteHistoryMessage: "La cronologia delle chat viene salvata solo su questo dispositivo. Eliminare tutta la cronologia non può essere annullato.\n\n(Davvero non può essere annullato 😊~)\n\nConferma se vuoi eliminare tutta la cronologia.",
            .settingsDeleteHistoryConfirm: "Elimina",
            .settingsRestoreDefaults: "Ripristina impostazioni predefinite",
            .settingsRestoreDefaultsAction: "Ripristina",
            .settingsRestoreDefaultsTitle: "Ripristina impostazioni predefinite",
            .settingsRestoreDefaultsMessage: "Ripristina le impostazioni predefinite di lingua, tema, opzione del titolo chat, stile chat e lunghezza del contesto.\n\nQuesta azione non può essere annullata.",
            .settingsRestoreDefaultsConfirm: "Conferma",
            .appearanceLight: "Chiaro",
            .appearanceDark: "Scuro",
            .appearanceSystem: "Segui sistema",
            .chatTitleModeContent: "Contenuto della chat come titolo",
            .chatTitleModeAI: "IA genera titoli per le nuove chat",
            .chatStyleDefault: "Predefinito",
            .chatStyleEfficiency: "Efficiente",
            .chatStyleEnthusiasm: "Entusiasta",
            .chatStyleGentle: "Gentile",
            .chatStyleSerious: "Serio",
            .sidebarHistory: "Cronologia chat locale",
            .sidebarNewConversation: "Nuova chat",
            .sidebarEmptyHistory: "Nessuna cronologia locale disponibile",
            .sidebarSettings: "Impostazioni",
            .moduleStatusWaiting: "In attesa",
            .moduleStatusLoading: "Caricamento",
            .moduleStatusReady: "Pronto",
            .moduleStatusError: "Errore",
            .moduleLoad: "Carica",
            .moduleUnload: "Scarica",
            .moduleLoadingOverlay: "Caricamento",
            .contextLengthTitle: "Lunghezza del contesto",
            .contextLengthShort: "Chat breve",
            .contextLengthMedium: "Chat media",
            .contextLengthLong: "Chat lunga",
            .contextLengthCustom: "Personalizzato",
            .contextLengthCustomPlaceholder: "Inserisci il numero di token",
            .contextLengthCustomMessage: "Intervallo: 100–262143",
            .contextLengthCustomWarning: "Un contesto troppo breve (<4K) causerà l'interruzione prematura delle conversazioni, risultando in un'esperienza scadente.\n\nUn contesto troppo lungo (>32K) esercita una pressione eccessiva sull'hardware del dispositivo e può causare surriscaldamento, rallentamenti o arresti anomali.\n\nSi prega di bilanciare le proprie esigenze personali e le capacità del dispositivo nell'impostare il contesto massimo, e di accettare i possibili effetti negativi.",
            .contextLengthCustomWarningConfirm: "Ho capito",
            .reasoningThinking: "Pensiero",
            .reasoningDirect: "Diretta",
            .attachmentPickImage: "Seleziona immagini",
            .composerPlaceholder: "Scrivi un messaggio...",
            .renameTitle: "Titolo personalizzato",
            .renamePlaceholder: "Inserisci un titolo personalizzato",
            .commonCancel: "Annulla",
            .commonSave: "Salva",
            .renameMessage: "Imposta un titolo più breve per questa conversazione.",
            .historyCustomTitle: "Titolo personalizzato",
            .historyAITitleGenerate: "Genera titolo IA",
            .historyAITitleGenerating: "Generazione titolo",
            .historyDeleteConversation: "Elimina conversazione",
            .gallerySelectedImages: "Immagini selezionate",
            .galleryConversationImages: "Immagini della conversazione",
            .assistantStoppedThinking: "(L'utente ha interrotto il mio ragionamento)",
            .attachmentImageProcessingWait: "(Elaborazione in corso, attendi con pazienza)",
            .attachmentImageProcessingStopped: "L'utente ha interrotto l'analisi dell'immagine. Per continuare, carica di nuovo l'immagine.",
            .attachmentImageWarning: "Il modello attuale ha una comprensione limitata delle immagini. Ogni immagine consuma una quantità significativa di token di contesto. Quando le immagini sono allegate, il modello passerà automaticamente alla modalità risposta diretta (il pensiero viene disabilitato).\n\nSi prega di tenere presenti queste limitazioni.",
            .attachmentImageWarningConfirm: "Ho capito",
            .settingsThinkingMode: "Modalità pensiero",
            .thinkingModeEnabled: "Attivata",
            .thinkingModeDisabled: "Disattivata",
            .thinkingModeWarning: "La modalità pensiero consente al modello di ragionare passo dopo passo prima di rispondere, il che può migliorare la qualità delle risposte per domande complesse.\n\nTuttavia, la modalità pensiero aumenta significativamente il consumo di token e il tempo di generazione. Su dispositivi con hardware limitato, potrebbe causare ritardi evidenti o surriscaldamento.\n\nSi prega di bilanciare le esigenze di qualità e le capacità del dispositivo.",
            .thinkingModeWarningConfirm: "Attiva",
            .thinkingModeLockedHint: "La modalità pensiero è attualmente disattivata. Si prega di attivarla prima nelle impostazioni."
        ],
        .turkish: [
            .settingsTitle: "Ayarlar",
            .settingsLanguage: "Dil",
            .settingsAppearance: "Tema",
            .settingsChatTitle: "Sohbet başlığı",
            .settingsChatStyle: "Sohbet tarzı",
            .settingsLanguageAuto: "Otomatik (%@)",
            .settingsDeleteHistory: "Geçmişi sil",
            .settingsDeleteHistoryAction: "Sil",
            .settingsDeleteHistoryTitle: "Tüm yerel geçmişi sil",
            .settingsDeleteHistoryMessage: "Sohbet geçmişi yalnızca bu cihazda saklanır. Tüm geçmişi sildikten sonra geri alınamaz.\n\n(Bu gerçekten geri alınamaz 😊~)\n\nLütfen tüm geçmişi silmek istediğinizi onaylayın.",
            .settingsDeleteHistoryConfirm: "Sil",
            .settingsRestoreDefaults: "Varsayılan ayarları geri yükle",
            .settingsRestoreDefaultsAction: "Geri yükle",
            .settingsRestoreDefaultsTitle: "Varsayılan ayarları geri yükle",
            .settingsRestoreDefaultsMessage: "Dil, tema rengi, sohbet başlığı seçeneği, sohbet tarzı ve bağlam uzunluğu seçeneklerini varsayılanlara geri yükleyin.\n\nBu işlem geri alınamaz.",
            .settingsRestoreDefaultsConfirm: "Onayla",
            .appearanceLight: "Açık",
            .appearanceDark: "Koyu",
            .appearanceSystem: "Sistemi izle",
            .chatTitleModeContent: "Varsayılan sohbet içeriği başlık",
            .chatTitleModeAI: "Yeni sohbetler için YZ otomatik başlık",
            .chatStyleDefault: "Varsayılan",
            .chatStyleEfficiency: "Verimli",
            .chatStyleEnthusiasm: "Coşkulu",
            .chatStyleGentle: "Nazik",
            .chatStyleSerious: "Ciddi",
            .sidebarHistory: "Yerel sohbet geçmişi",
            .sidebarNewConversation: "Yeni sohbet",
            .sidebarEmptyHistory: "Henüz yerel geçmiş yok",
            .sidebarSettings: "Ayarlar",
            .moduleStatusWaiting: "Bekliyor",
            .moduleStatusLoading: "Yükleniyor",
            .moduleStatusReady: "Hazır",
            .moduleStatusError: "Hata",
            .moduleLoad: "Yükle",
            .moduleUnload: "Boşalt",
            .moduleLoadingOverlay: "Yükleniyor",
            .contextLengthTitle: "Bağlam uzunluğu",
            .contextLengthShort: "Kısa sohbet",
            .contextLengthMedium: "Orta sohbet",
            .contextLengthLong: "Uzun sohbet",
            .contextLengthCustom: "Özel",
            .contextLengthCustomPlaceholder: "Token sayısını girin",
            .contextLengthCustomMessage: "Aralık: 100–262143",
            .contextLengthCustomWarning: "Çok kısa bir bağlam (<4K) konuşmaların erken kesilmesine neden olarak kötü bir deneyime yol açar.\n\nÇok uzun bir bağlam (>32K) cihaz donanımına aşırı baskı uygular ve aşırı ısınma, gecikme veya çökmelere neden olabilir.\n\nLütfen kişisel ihtiyaçlarınızı ve cihazınızın kapasitesini dengeleyerek uygun bir maksimum bağlam belirleyin ve olası olumsuz etkileri kabul edin.",
            .contextLengthCustomWarningConfirm: "Anladım",
            .reasoningThinking: "Düşünme",
            .reasoningDirect: "Doğrudan",
            .attachmentPickImage: "Görsel seç",
            .composerPlaceholder: "Mesaj yaz...",
            .renameTitle: "Özel başlık",
            .renamePlaceholder: "Özel başlık girin",
            .commonCancel: "İptal",
            .commonSave: "Kaydet",
            .renameMessage: "Bu sohbet için daha kısa bir başlık belirleyin.",
            .historyCustomTitle: "Özel başlık",
            .historyAITitleGenerate: "YZ başlığı oluştur",
            .historyAITitleGenerating: "Başlık oluşturuluyor",
            .historyDeleteConversation: "Sohbeti sil",
            .gallerySelectedImages: "Seçilen görseller",
            .galleryConversationImages: "Sohbet görselleri",
            .assistantStoppedThinking: "(Kullanıcı düşünmemi durdurdu)",
            .attachmentImageProcessingWait: "(İşleniyor, lütfen sabırla bekleyin)",
            .attachmentImageProcessingStopped: "Kullanıcı görseli analiz etmemi durdurdu. Devam etmek istiyorsanız lütfen görseli yeniden yükleyin.",
            .attachmentImageWarning: "Mevcut modelin görsel anlama yeteneği sınırlıdır. Her görsel önemli miktarda bağlam tokeni tüketir. Görseller eklendiğinde, model otomatik olarak doğrudan yanıt moduna geçecektir (düşünme devre dışı bırakılır).\n\nLütfen bu sınırlamaları dikkate alın.",
            .attachmentImageWarningConfirm: "Anladım",
            .settingsThinkingMode: "Düşünme modu",
            .thinkingModeEnabled: "Etkin",
            .thinkingModeDisabled: "Devre dışı",
            .thinkingModeWarning: "Düşünme modu, modelin yanıt vermeden önce adım adım akıl yürütmesine olanak tanır, bu da karmaşık sorular için yanıt kalitesini artırabilir.\n\nAncak düşünme modu, token tüketimini ve oluşturma süresini önemli ölçüde artırır. Sınırlı donanıma sahip cihazlarda belirgin gecikmelere veya aşırı ısınmaya neden olabilir.\n\nLütfen kalite ihtiyaçlarını ve cihaz kapasitesini dengeleyin.",
            .thinkingModeWarningConfirm: "Etkinleştir",
            .thinkingModeLockedHint: "Düşünme modu şu anda devre dışıdır. Lütfen önce Ayarlar'dan etkinleştirin."
        ],
        .vietnamese: [
            .settingsTitle: "Cài đặt",
            .settingsLanguage: "Ngôn ngữ",
            .settingsAppearance: "Giao diện",
            .settingsChatTitle: "Tiêu đề chat",
            .settingsChatStyle: "Phong cách chat",
            .settingsLanguageAuto: "Tự động (%@)",
            .settingsDeleteHistory: "Xóa lịch sử",
            .settingsDeleteHistoryAction: "Xóa",
            .settingsDeleteHistoryTitle: "Xóa toàn bộ lịch sử cục bộ",
            .settingsDeleteHistoryMessage: "Lịch sử trò chuyện chỉ được lưu trên thiết bị này. Xóa toàn bộ lịch sử sẽ không thể hoàn tác.\n\n(Thật sự không thể hoàn tác đâu 😊~)\n\nVui lòng xác nhận bạn muốn xóa toàn bộ lịch sử.",
            .settingsDeleteHistoryConfirm: "Xóa",
            .settingsRestoreDefaults: "Khôi phục mặc định",
            .settingsRestoreDefaultsAction: "Khôi phục",
            .settingsRestoreDefaultsTitle: "Khôi phục cài đặt mặc định",
            .settingsRestoreDefaultsMessage: "Khôi phục cài đặt mặc định cho ngôn ngữ, màu chủ đề, tùy chọn tiêu đề chat, phong cách chat và độ dài ngữ cảnh.\n\nThao tác này không thể hoàn tác.",
            .settingsRestoreDefaultsConfirm: "Xác nhận",
            .appearanceLight: "Sáng",
            .appearanceDark: "Tối",
            .appearanceSystem: "Theo hệ thống",
            .chatTitleModeContent: "Nội dung chat làm tiêu đề mặc định",
            .chatTitleModeAI: "AI tự tạo tiêu đề cho chat mới",
            .chatStyleDefault: "Mặc định",
            .chatStyleEfficiency: "Hiệu quả",
            .chatStyleEnthusiasm: "Nhiệt tình",
            .chatStyleGentle: "Dịu dàng",
            .chatStyleSerious: "Nghiêm túc",
            .sidebarHistory: "Lịch sử chat cục bộ",
            .sidebarNewConversation: "Cuộc trò chuyện mới",
            .sidebarEmptyHistory: "Chưa có lịch sử cục bộ",
            .sidebarSettings: "Cài đặt",
            .moduleStatusWaiting: "Chờ",
            .moduleStatusLoading: "Đang tải",
            .moduleStatusReady: "Sẵn sàng",
            .moduleStatusError: "Lỗi",
            .moduleLoad: "Tải",
            .moduleUnload: "Gỡ tải",
            .moduleLoadingOverlay: "Đang tải",
            .contextLengthTitle: "Độ dài ngữ cảnh",
            .contextLengthShort: "Chat ngắn",
            .contextLengthMedium: "Chat vừa",
            .contextLengthLong: "Chat dài",
            .contextLengthCustom: "Tùy chỉnh",
            .contextLengthCustomPlaceholder: "Nhập số lượng token",
            .contextLengthCustomMessage: "Phạm vi: 100–262143",
            .contextLengthCustomWarning: "Ngữ cảnh quá ngắn (<4K) sẽ khiến cuộc trò chuyện bị cắt sớm, dẫn đến trải nghiệm kém.\n\nNgữ cảnh quá dài (>32K) gây áp lực quá lớn lên phần cứng thiết bị và có thể gây ra hiện tượng nóng máy, giật lag hoặc thoát ứng dụng đột ngột.\n\nVui lòng cân nhắc nhu cầu cá nhân và cấu hình thiết bị của bạn để đặt ngữ cảnh tối đa phù hợp, và chấp nhận các tác động tiêu cực có thể xảy ra.",
            .contextLengthCustomWarningConfirm: "Tôi đã hiểu",
            .reasoningThinking: "Suy nghĩ",
            .reasoningDirect: "Trực tiếp",
            .attachmentPickImage: "Chọn ảnh",
            .composerPlaceholder: "Nhập tin nhắn...",
            .renameTitle: "Tiêu đề tùy chỉnh",
            .renamePlaceholder: "Nhập tiêu đề tùy chỉnh",
            .commonCancel: "Hủy",
            .commonSave: "Lưu",
            .renameMessage: "Đặt tiêu đề ngắn hơn cho cuộc trò chuyện này.",
            .historyCustomTitle: "Tiêu đề tùy chỉnh",
            .historyAITitleGenerate: "Tạo tiêu đề AI",
            .historyAITitleGenerating: "Đang tạo tiêu đề",
            .historyDeleteConversation: "Xóa cuộc trò chuyện",
            .gallerySelectedImages: "Ảnh đã chọn",
            .galleryConversationImages: "Ảnh cuộc trò chuyện",
            .assistantStoppedThinking: "(Người dùng đã dừng phần suy nghĩ của tôi)",
            .attachmentImageProcessingWait: "(Đang xử lý, vui lòng kiên nhẫn chờ)",
            .attachmentImageProcessingStopped: "Người dùng đã dừng việc phân tích hình ảnh. Nếu muốn tiếp tục, vui lòng tải ảnh lên lại.",
            .attachmentImageWarning: "Mô hình hiện tại có khả năng hiểu hình ảnh hạn chế. Mỗi hình ảnh tiêu tốn một lượng lớn token ngữ cảnh. Khi đính kèm hình ảnh, mô hình sẽ tự động chuyển sang chế độ trả lời trực tiếp (tính năng suy nghĩ bị tắt).\n\nVui lòng lưu ý các hạn chế này.",
            .attachmentImageWarningConfirm: "Tôi đã hiểu",
            .settingsThinkingMode: "Chế độ suy nghĩ",
            .thinkingModeEnabled: "Đã bật",
            .thinkingModeDisabled: "Đã tắt",
            .thinkingModeWarning: "Chế độ suy nghĩ cho phép mô hình lý luận từng bước trước khi trả lời, có thể cải thiện chất lượng câu trả lời cho các câu hỏi phức tạp.\n\nTuy nhiên, chế độ suy nghĩ làm tăng đáng kể mức tiêu thụ token và thời gian tạo. Trên các thiết bị có phần cứng hạn chế, có thể gây ra độ trễ rõ rệt hoặc quá nóng.\n\nVui lòng cân nhắc giữa nhu cầu chất lượng và khả năng thiết bị.",
            .thinkingModeWarningConfirm: "Bật",
            .thinkingModeLockedHint: "Chế độ suy nghĩ hiện đang tắt. Vui lòng bật trong Cài đặt trước."
        ],
        .kazakh: [
            .settingsTitle: "Баптаулар",
            .settingsLanguage: "Тіл",
            .settingsAppearance: "Тақырып",
            .settingsChatTitle: "Чат тақырыбы",
            .settingsChatStyle: "Чат стилі",
            .settingsLanguageAuto: "Авто (%@)",
            .settingsDeleteHistory: "Тарихты жою",
            .settingsDeleteHistoryAction: "Жою",
            .settingsDeleteHistoryTitle: "Барлық жергілікті тарихты жою",
            .settingsDeleteHistoryMessage: "Чат тарихы тек осы құрылғыда сақталады. Барлық тарихты жойғаннан кейін оны қайтару мүмкін емес.\n\n(Шынымен қайтаруға болмайды 😊~)\n\nБарлық тарихты жойғыңыз келетінін растаңыз.",
            .settingsDeleteHistoryConfirm: "Жою",
            .settingsRestoreDefaults: "Әдепкі баптауларды қалпына келтіру",
            .settingsRestoreDefaultsAction: "Қалпына келтіру",
            .settingsRestoreDefaultsTitle: "Әдепкі баптауларды қалпына келтіру",
            .settingsRestoreDefaultsMessage: "Тіл, тақырып түсі, чат тақырыбының параметрі, чат стилі және контекст ұзындығы параметрлерін әдепкі күйіне қайтару.\n\nБұл әрекетті кері қайтару мүмкін емес.",
            .settingsRestoreDefaultsConfirm: "Растау",
            .appearanceLight: "Жарық",
            .appearanceDark: "Қараңғы",
            .appearanceSystem: "Жүйе бойынша",
            .chatTitleModeContent: "Әдепкі чат мазмұнын тақырып ету",
            .chatTitleModeAI: "Жаңа чаттарға ЖИ автоматты тақырып",
            .chatStyleDefault: "Әдепкі",
            .chatStyleEfficiency: "Тиімді",
            .chatStyleEnthusiasm: "Ынталы",
            .chatStyleGentle: "Жұмсақ",
            .chatStyleSerious: "Салмақты",
            .sidebarHistory: "Жергілікті чат тарихы",
            .sidebarNewConversation: "Жаңа чат",
            .sidebarEmptyHistory: "Әзірге жергілікті тарих жоқ",
            .sidebarSettings: "Баптаулар",
            .moduleStatusWaiting: "Күту",
            .moduleStatusLoading: "Жүктелуде",
            .moduleStatusReady: "Дайын",
            .moduleStatusError: "Қате",
            .moduleLoad: "Жүктеу",
            .moduleUnload: "Жадтан шығару",
            .moduleLoadingOverlay: "Жүктелуде",
            .contextLengthTitle: "Контекст ұзындығы",
            .contextLengthShort: "Қысқа чат",
            .contextLengthMedium: "Орта чат",
            .contextLengthLong: "Ұзын чат",
            .contextLengthCustom: "Реттелмелі",
            .contextLengthCustomPlaceholder: "Токен санын енгізіңіз",
            .contextLengthCustomMessage: "Аралық: 100–262143",
            .contextLengthCustomWarning: "Тым қысқа контекст (<4K) әңгімелердің ерте үзілуіне әкеліп, нашар тәжірибе береді.\n\nТым ұзын контекст (>32K) құрылғының аппараттық құралына шамадан тыс жүктеме түсіріп, қызуға, кідіріске немесе қосымшаның күтпеген жабылуына әкелуі мүмкін.\n\nЖеке қажеттіліктеріңіз бен құрылғыңыздың мүмкіндіктерін ескере отырып, тиісті максималды контекстті орнатыңыз және ықтимал теріс салдарды қабылдаңыз.",
            .contextLengthCustomWarningConfirm: "Түсіндім",
            .reasoningThinking: "Ойлау",
            .reasoningDirect: "Тікелей",
            .attachmentPickImage: "Сурет таңдау",
            .composerPlaceholder: "Хабарлама жазыңыз...",
            .renameTitle: "Арнайы тақырып",
            .renamePlaceholder: "Арнайы тақырып енгізіңіз",
            .commonCancel: "Бас тарту",
            .commonSave: "Сақтау",
            .renameMessage: "Осы чатқа қысқалау тақырып орнатыңыз.",
            .historyCustomTitle: "Арнайы тақырып",
            .historyAITitleGenerate: "ЖИ тақырыбын жасау",
            .historyAITitleGenerating: "Тақырып жасалуда",
            .historyDeleteConversation: "Чатты жою",
            .gallerySelectedImages: "Таңдалған суреттер",
            .galleryConversationImages: "Чат суреттері",
            .assistantStoppedThinking: "(Пайдаланушы менің ойлауымды тоқтатты)",
            .attachmentImageProcessingWait: "(Өңделіп жатыр, сабырмен күте тұрыңыз)",
            .attachmentImageProcessingStopped: "Пайдаланушы суретті талдауды тоқтатты. Жалғастыру үшін суретті қайта жүктеңіз.",
            .attachmentImageWarning: "Ағымдағы модельдің кескіндерді түсіну мүмкіндігі шектеулі. Әрбір кескін контекст токендерінің көп мөлшерін тұтынады. Кескіндер тіркелгенде, модель автоматты түрде тікелей жауап режиміне ауысады (ойлау өшіріледі).\n\nОсы шектеулерді ескеріңіз.",
            .attachmentImageWarningConfirm: "Түсіндім",
            .settingsThinkingMode: "Ойлау режимі",
            .thinkingModeEnabled: "Қосулы",
            .thinkingModeDisabled: "Өшірулі",
            .thinkingModeWarning: "Ойлау режимі модельге жауап бермес бұрын кезең-кезеңмен ойлауға мүмкіндік береді, бұл күрделі сұрақтарға жауап сапасын жақсарта алады.\n\nАлайда, ойлау режимі токен тұтынуды және генерация уақытын айтарлықтай арттырады. Аппараттық мүмкіндіктері шектеулі құрылғыларда айқын кідіріс немесе қызуға себеп болуы мүмкін.\n\nСапа талаптары мен құрылғы мүмкіндіктерін теңестіріңіз.",
            .thinkingModeWarningConfirm: "Қосу",
            .thinkingModeLockedHint: "Ойлау режимі қазір өшірулі. Алдымен оны баптауларда қосыңыз."
        ],
        .kyrgyz: [
            .settingsTitle: "Жөндөөлөр",
            .settingsLanguage: "Тил",
            .settingsAppearance: "Тема",
            .settingsChatTitle: "Чат аталышы",
            .settingsChatStyle: "Чат стили",
            .settingsLanguageAuto: "Авто (%@)",
            .settingsDeleteHistory: "Тарыхты өчүрүү",
            .settingsDeleteHistoryAction: "Өчүрүү",
            .settingsDeleteHistoryTitle: "Бардык жергиликтүү тарыхты өчүрүү",
            .settingsDeleteHistoryMessage: "Чат тарыхы ушул түзмөктө гана сакталат. Бардык тарыхты өчүргөндөн кийин аны кайтаруу мүмкүн эмес.\n\n(Чынында эле кайтарууга болбойт 😊~)\n\nБардык тарыхты өчүрүүнү ырастаңыз.",
            .settingsDeleteHistoryConfirm: "Өчүрүү",
            .settingsRestoreDefaults: "Демейки жөндөөлөрдү калыбына келтирүү",
            .settingsRestoreDefaultsAction: "Калыбына келтирүү",
            .settingsRestoreDefaultsTitle: "Демейки жөндөөлөрдү калыбына келтирүү",
            .settingsRestoreDefaultsMessage: "Тил, тема түсү, чат аталышынын тандоосу, чат стили жана контекст узундугу үчүн демейки жөндөөлөрдү калыбына келтирүү.\n\nБул аракетти артка кайтарууга болбойт.",
            .settingsRestoreDefaultsConfirm: "Ырастоо",
            .appearanceLight: "Жарык",
            .appearanceDark: "Караңгы",
            .appearanceSystem: "Системага ылайык",
            .chatTitleModeContent: "Демейки чат мазмунун аталыш кылуу",
            .chatTitleModeAI: "Жаңы чаттарга ЖИ автоматтык аталыш",
            .chatStyleDefault: "Демейки",
            .chatStyleEfficiency: "Натыйжалуу",
            .chatStyleEnthusiasm: "Шыктандыруучу",
            .chatStyleGentle: "Жумшак",
            .chatStyleSerious: "Олуттуу",
            .sidebarHistory: "Жергиликтүү чат тарыхы",
            .sidebarNewConversation: "Жаңы чат",
            .sidebarEmptyHistory: "Азырынча жергиликтүү тарых жок",
            .sidebarSettings: "Жөндөөлөр",
            .moduleStatusWaiting: "Күтүү",
            .moduleStatusLoading: "Жүктөлүүдө",
            .moduleStatusReady: "Даяр",
            .moduleStatusError: "Ката",
            .moduleLoad: "Жүктөө",
            .moduleUnload: "Жүктөөдөн чыгаруу",
            .moduleLoadingOverlay: "Жүктөлүүдө",
            .contextLengthTitle: "Контекст узундугу",
            .contextLengthShort: "Кыска чат",
            .contextLengthMedium: "Орто чат",
            .contextLengthLong: "Узун чат",
            .contextLengthCustom: "Ыңгайлаштыруу",
            .contextLengthCustomPlaceholder: "Токен санын киргизиңиз",
            .contextLengthCustomMessage: "Диапазон: 100–262143",
            .contextLengthCustomWarning: "Өтө кыска контекст (<4K) сүйлөшүүлөрдүн эрте үзүлүшүнө алып келип, начар тажрыйба берет.\n\nӨтө узун контекст (>32K) түзмөктүн аппараттык каражаттарына ашыкча жүк түшүрүп, ысып кетүүгө, кечигүүгө же колдонмонун күтүүсүз жабылышына алып келиши мүмкүн.\n\nЖеке муктаждыктарыңызды жана түзмөгүңүздүн мүмкүнчүлүктөрүн эске алып, ылайыктуу максималдуу контекстти орнотуңуз жана болушу мүмкүн болгон терс натыйжаларды кабыл алыңыз.",
            .contextLengthCustomWarningConfirm: "Түшүндүм",
            .reasoningThinking: "Ойлонуу",
            .reasoningDirect: "Түз жооп",
            .attachmentPickImage: "Сүрөт тандоо",
            .composerPlaceholder: "Билдирүү жазыңыз...",
            .renameTitle: "Ыңгайлаштырылган аталыш",
            .renamePlaceholder: "Ыңгайлаштырылган аталышты киргизиңиз",
            .commonCancel: "Жокко чыгаруу",
            .commonSave: "Сактоо",
            .renameMessage: "Бул маек үчүн кыскараак аталыш коюңуз.",
            .historyCustomTitle: "Ыңгайлаштырылган аталыш",
            .historyAITitleGenerate: "ЖИ аталышын түзүү",
            .historyAITitleGenerating: "Аталыш түзүлүүдө",
            .historyDeleteConversation: "Маекти өчүрүү",
            .gallerySelectedImages: "Тандалган сүрөттөр",
            .galleryConversationImages: "Маектин сүрөттөрү",
            .assistantStoppedThinking: "(Колдонуучу менин ой жүгүртүшүмдү токтотту)",
            .attachmentImageProcessingWait: "(Иштелүүдө, сабыр кылып күтө туруңуз)",
            .attachmentImageProcessingStopped: "Колдонуучу сүрөттү талдоону токтотту. Улантуу үчүн сүрөттү кайра жүктөңүз.",
            .attachmentImageWarning: "Учурдагы моделдин сүрөттөрдү түшүнүү жөндөмдүүлүгү чектелген. Ар бир сүрөт контекст токендеринин чоң көлөмүн колдонот. Сүрөттөр тиркелгенде, модель автоматтык түрдө түз жооп режимине өтөт (ой жүгүртүү өчүрүлөт).\n\nБул чектөөлөрдү эске алыңыз.",
            .attachmentImageWarningConfirm: "Түшүндүм",
            .settingsThinkingMode: "Ой жүгүртүү режими",
            .thinkingModeEnabled: "Иштетилген",
            .thinkingModeDisabled: "Өчүрүлгөн",
            .thinkingModeWarning: "Ой жүгүртүү режими моделге жооп берүүдөн мурун кадам-кадам менен ойлонууга мүмкүнчүлүк берет, бул татаал суроолорго жооптун сапатын жакшыртат.\n\nБирок, ой жүгүртүү режими токен колдонууну жана түзүү убактысын бир топ көбөйтөт. Аппараттык мүмкүнчүлүктөрү чектелүү түзмөктөрдө байкалаарлык кечигүү же ысып кетүү пайда болушу мүмкүн.\n\nСапат муктаждыктары менен түзмөктүн мүмкүнчүлүктөрүн тең салмактаңыз.",
            .thinkingModeWarningConfirm: "Иштетүү",
            .thinkingModeLockedHint: "Ой жүгүртүү режими азыр өчүрүлгөн. Алгач жөндөөлөрдөн иштетиңиз."
        ]
    ]
}
